# Generated by Django 4.1.6 on 2023-02-04 07:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('code', models.CharField(help_text='Unique reference given by the author.', max_length=128, unique=True)),
                ('is_available', models.BooleanField(default=False, help_text='If TRUE, then record is available')),
                ('name', models.CharField(help_text='Name of product.', max_length=256)),
                ('price', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Price per product. This is the unit price of the product.', max_digits=12, verbose_name='Price')),
                ('in_stock', models.PositiveIntegerField(default=0, help_text='Amount of available products.')),
                ('short_description', models.TextField(blank=True, default='', help_text='Short summary, can be used in search results.')),
                ('long_description', models.TextField(blank=True, default='', help_text='Long Description')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('code', models.CharField(help_text='Unique reference given by the author.', max_length=128, unique=True)),
                ('is_available', models.BooleanField(default=False, help_text='If TRUE, then record is available')),
                ('name', models.CharField(help_text='Name of the Product Type.', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the Product Type.')),
                ('category', models.CharField(choices=[('none', 'User defined'), ('shirt', 'Shirt'), ('sports', 'Sports')], default='none', max_length=32)),
            ],
            options={
                'ordering': ['-id', 'name', 'category'],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name', 'is_available', 'category'], name='product_pro_name_c3bb88_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(help_text='Related Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='product.productcategory'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code', 'name', 'product_category', 'in_stock'], name='product_pro_code_a4bc7c_idx'),
        ),
    ]
