# Generated by Django 4.1.6 on 2023-02-04 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Discount Price per product.', max_digits=12, null=True, verbose_name='Discount price'),
        ),
    ]
