# Generated by Django 4.1.6 on 2023-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('danger', 'Danger')], default='primary', max_length=32),
        ),
    ]
